<?php
session_start();
$nome = filter_input(INPUT_POST, 'nome', FILTER_SANITIZE_SPECIAL_CHARS);
if($nome){
    $_SESSION['usuario'] = $nome;
    header('Location: index.php');
    exit;
}else{
    $_SESSION['alerta'] = 'Preencha o nome do usuário';
    header('Location:login.php');
    exit;
}
/*
1 - CRIEI 3 PAGINAS: INDEX, LOGIN E RECEBE;
2 - NA INDEX, CONFIGUREI UM LINK SAIR, UM LINK LOGIN e UMA SAUDAÇAO COM NOME DO USUÁRIO LOGADO;
3 - CRIEI UM FORM NA PAGINA DE LOGIN QUE ENVIA OS DADOS PARA RECEBE VIA POST;
4 - NA PAGINA RECEBE ARMAZENO OS DADOS APLICANDO UM FILTRO DE CARACTER ESPECIAL;
5 - INICIO A SESSAO EM TODAS AS 3 PAGINAS;
6 - NA PAGINA RECEBE VERIFICO SE O DADO SOLICITADO FOI PREENCHIDO,
SE EXISTE, ARMAZENO A SESSAO COM OS DADOS E REDIRECIONO PARA A INDEX,
CASO CONTRÁRIO, ARMAZENO UMA SESSAO COM MSG E REDIRECIONO PRO LOGIN.
7 - NA INDEX, VERIFICO SE EXISTE A SESSAO E EXIBO O DADO COM SAUDAÇAO;
8 - NA TELA DE LOGIN, VERIFICO SE ESTÁ SETADA A SESSAO DA MSG E EXIBO A MSG;
OBS:
    1 - SOMENTE FAZER O REDIRECIONAMENTO DE PÁGINA, ANTES DE ENVIAR OU EXIBIR QUALQUER COISA;
    2 - SEMPRE DEPOIS DA HEADER LOCATION EXECUTAR O EXIT;*/
